-- A estrutura desta migration depende de WebscrapingCampaign e
-- WebscrapingCampaignBatch. Como a ordenacao lexicografica executa esta pasta
-- antes de 20260506_radar_campaigns_database, o DDL foi movido para o final
-- daquela migration para manter a criacao de bancos novos deterministica.
