ALTER TABLE "RadarLeadPool" ADD COLUMN IF NOT EXISTS "evidenceJson" TEXT;
ALTER TABLE "RadarLeadPool" ADD COLUMN IF NOT EXISTS "rejectReasons" TEXT;
ALTER TABLE "RadarLeadPool" ADD COLUMN IF NOT EXISTS "qualityReason" TEXT;
ALTER TABLE "RadarLeadPool" ADD COLUMN IF NOT EXISTS "visibilityTier" TEXT;
ALTER TABLE "RadarLeadPool" ADD COLUMN IF NOT EXISTS "deliveryProduct" TEXT;
ALTER TABLE "WebscrapingSourceQuality" ADD COLUMN IF NOT EXISTS "approvalRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
