INSERT INTO "WebscrapingOperationalConfig" (
  "key",
  "enabled",
  "preset",
  "startHour",
  "startMinute",
  "endHour",
  "endMinute",
  "engineCount",
  "intensity",
  "memoryTargetGb",
  "batchSize",
  "maxAttemptsPerTask",
  "engineUrlsJson",
  "createdAt",
  "updatedAt"
) VALUES (
  'turbo_noturno',
  true,
  'turbo_noturno',
  20,
  0,
  8,
  0,
  4,
  'turbo',
  16,
  20,
  3,
  '["http://localhost:8001","http://localhost:8002","http://localhost:8003","http://localhost:8004"]',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("key") DO UPDATE SET
  "enabled" = EXCLUDED."enabled",
  "preset" = EXCLUDED."preset",
  "startHour" = EXCLUDED."startHour",
  "startMinute" = EXCLUDED."startMinute",
  "endHour" = EXCLUDED."endHour",
  "endMinute" = EXCLUDED."endMinute",
  "engineCount" = EXCLUDED."engineCount",
  "intensity" = EXCLUDED."intensity",
  "memoryTargetGb" = EXCLUDED."memoryTargetGb",
  "batchSize" = EXCLUDED."batchSize",
  "maxAttemptsPerTask" = EXCLUDED."maxAttemptsPerTask",
  "engineUrlsJson" = EXCLUDED."engineUrlsJson",
  "updatedAt" = CURRENT_TIMESTAMP;
