ALTER TABLE "VendasLead" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "VendasLead" ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION;
ALTER TABLE "VendasLead" ADD COLUMN IF NOT EXISTS "reviews" INTEGER NOT NULL DEFAULT 0;
