export const VIDEO_TARGETS = Object.freeze({
  commercial: {
    title: 'HBX Entregas — vídeo comercial',
    scenes: [
      {
        id: 'opening',
        source: 'opening',
        duration: 7.2,
        title: 'HBX Entregas',
        narration: 'Sua operação de entregas, conectada do começo ao fim.',
      },
      {
        id: 'today',
        source: 'app',
        route: '/entrega',
        scenario: 'standard',
        duration: 5.2,
        caption: { eyebrow: 'ROTA DO DIA', title: 'Tudo o que precisa ser entregue, em uma única tela.', position: 'top' },
        narration: 'Veja a rota do dia, o que já foi entregue e a previsão de término.',
      },
      {
        id: 'clients',
        source: 'app',
        route: '/entrega/clientes',
        scenario: 'standard',
        action: 'client-search-open',
        duration: 7.4,
        caption: { eyebrow: 'CLIENTES', title: 'Endereço, dia de entrega e forma de pagamento organizados.', position: 'top' },
        narration: 'Cadastre clientes, endereços, dias de entrega e a forma de pagamento de cada um.',
      },
      {
        id: 'products',
        source: 'app',
        route: '/entrega/produtos',
        scenario: 'standard',
        action: 'product-open',
        duration: 5.8,
        caption: { eyebrow: 'PRODUTOS', title: 'Catálogo e preços prontos para a operação.', position: 'top' },
        narration: 'Mantenha seus produtos e preços prontos para cada entrega.',
      },
      {
        id: 'generate',
        source: 'app',
        route: '/entrega',
        scenario: 'standard',
        action: 'generate-preview',
        duration: 7.2,
        caption: { eyebrow: 'PLANEJAMENTO', title: 'Confira os clientes antes de colocar a equipe na rua.', position: 'top' },
        narration: 'Antes de começar, confira quem entra na rota e os itens de cada cliente.',
      },
      {
        id: 'route',
        source: 'app',
        route: '/entrega',
        scenario: 'standard',
        action: 'start-route',
        duration: 8.4,
        caption: { eyebrow: 'NA RUA', title: 'Próxima parada, horário e navegação sem improviso.', position: 'top' },
        narration: 'O entregador inicia a rota e recebe a próxima parada já organizada.',
      },
      {
        id: 'arrival',
        source: 'app',
        route: '/entrega',
        scenario: 'fresh-driver',
        prepare: 'route-ready',
        action: 'arrival-confirm',
        duration: 10.5,
        caption: { eyebrow: 'NA ENTREGA', title: 'Confira quantidade, recebimento e confirme em poucos toques.', position: 'top' },
        narration: 'Na chegada, confira a quantidade, registre o recebimento e confirme a entrega.',
      },
      {
        id: 'outro',
        source: 'card',
        duration: 5.2,
        card: {
          eyebrow: 'HBX SYSTEM',
          title: 'HBX Entregas',
          subtitle: 'Menos papel. Menos esquecimento. Mais controle da operação.',
          cta: 'Solicite uma demonstração',
        },
        narration: 'HBX Entregas. Sua operação na rota certa.',
      },
    ],
  },
  'tutorial-admin': {
    title: 'HBX Entregas — tutorial do administrador',
    scenes: [
      {
        id: 'admin-intro',
        source: 'card',
        duration: 4.2,
        card: { step: 'TUTORIAL DO ADMINISTRADOR', eyebrow: 'HBX ENTREGAS', title: 'Prepare a operação', subtitle: 'Clientes, produtos e rota do dia em uma sequência simples.' },
        narration: 'Neste tutorial, você vai preparar os cadastros e colocar a rota do dia para funcionar.',
      },
      {
        id: 'admin-clients',
        source: 'app',
        route: '/entrega/clientes',
        scenario: 'admin',
        action: 'client-search-open',
        duration: 8.5,
        caption: { eyebrow: 'PASSO 1', title: 'Confira o cadastro do cliente e o endereço de entrega.', position: 'top' },
        narration: 'Abra Clientes, localize a pessoa ou empresa e confira endereço, WhatsApp e dias de entrega.',
      },
      {
        id: 'admin-products',
        source: 'app',
        route: '/entrega/produtos',
        scenario: 'admin',
        action: 'product-open',
        duration: 7.0,
        caption: { eyebrow: 'PASSO 2', title: 'Cadastre produtos, unidade e preço.', position: 'top' },
        narration: 'Em Produtos, mantenha nome, unidade, preço e uso na logística atualizados.',
      },
      {
        id: 'admin-generate',
        source: 'app',
        route: '/entrega',
        scenario: 'admin',
        action: 'generate-preview',
        duration: 9.0,
        caption: { eyebrow: 'PASSO 3', title: 'Gere as entregas e confira a prévia da rota.', position: 'top' },
        narration: 'Na aba Rota, toque em Gerar entregas de hoje e confira os clientes e itens antes de começar.',
      },
      {
        id: 'admin-day',
        source: 'app',
        route: '/entrega',
        scenario: 'admin',
        duration: 6.0,
        caption: { eyebrow: 'PASSO 4', title: 'Acompanhe entregues, recebido e valores a receber.', position: 'top' },
        narration: 'Durante o dia, acompanhe o progresso, os recebimentos e o que ainda falta concluir.',
      },
      {
        id: 'admin-outro',
        source: 'card',
        duration: 4.5,
        card: { eyebrow: 'ADMINISTRAÇÃO PRONTA', title: 'A rota pode começar', subtitle: 'O entregador recebe a sequência no próprio celular.' },
        narration: 'Com os cadastros e a rota conferidos, a equipe já pode sair para entregar.',
      },
    ],
  },
  'tutorial-entregador': {
    title: 'HBX Entregas — tutorial do entregador',
    scenes: [
      {
        id: 'driver-intro',
        source: 'card',
        duration: 4.0,
        card: { step: 'TUTORIAL DO ENTREGADOR', eyebrow: 'HBX ENTREGAS', title: 'Da rota à confirmação', subtitle: 'Veja a próxima parada e registre a entrega sem papel.' },
        narration: 'Neste tutorial, você vai iniciar a rota, chegar ao cliente e confirmar a entrega.',
      },
      {
        id: 'driver-start',
        source: 'app',
        route: '/entrega',
        scenario: 'fresh-driver',
        action: 'start-route',
        duration: 9.0,
        caption: { eyebrow: 'PASSO 1', title: 'Confira o dia e toque em Iniciar rota.', position: 'top' },
        narration: 'Confira as entregas do dia e toque em Iniciar rota.',
      },
      {
        id: 'driver-stop',
        source: 'app',
        route: '/entrega',
        scenario: 'fresh-driver',
        prepare: 'route-ready',
        duration: 6.0,
        caption: { eyebrow: 'PASSO 2', title: 'Veja cliente, endereço, itens e previsão de chegada.', position: 'top' },
        narration: 'A tela mostra o cliente atual, endereço, itens e horário previsto.',
      },
      {
        id: 'driver-arrival',
        source: 'app',
        route: '/entrega',
        scenario: 'fresh-driver',
        prepare: 'route-ready',
        action: 'arrival-adjust',
        duration: 8.0,
        caption: { eyebrow: 'PASSO 3', title: 'Toque em Cheguei e confira a quantidade entregue.', position: 'top' },
        narration: 'Ao chegar, toque em Cheguei e ajuste a quantidade quando for necessário.',
      },
      {
        id: 'driver-confirm',
        source: 'app',
        route: '/entrega',
        scenario: 'fresh-driver',
        prepare: 'route-ready',
        action: 'arrival-confirm',
        duration: 11.0,
        caption: { eyebrow: 'PASSO 4', title: 'Registre o recebimento e confirme a entrega.', position: 'top' },
        narration: 'Escolha a forma de recebimento e toque em Entregue. O HBX salva e prepara a próxima parada.',
      },
      {
        id: 'driver-outro',
        source: 'card',
        duration: 4.5,
        card: { eyebrow: 'ROTA EM ANDAMENTO', title: 'Próxima parada', subtitle: 'Repita o mesmo fluxo até concluir o dia.' },
        narration: 'Depois da confirmação, siga para a próxima parada até concluir a rota.',
      },
    ],
  },
});
