var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/dashboard/master/assistente-tecnico/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4e89f29a._.js")
R.c("server/chunks/ssr/_07720ad9._.js")
R.c("server/chunks/ssr/_ac4bd4ef._.js")
R.c("server/chunks/ssr/[root-of-the-server]__cdb3e6d7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__081886e2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_81959fb0._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/src_app_global-error_tsx_aa661ba4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__f37271da._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/ce889_server_app_dashboard_master_assistente-tecnico_page_actions_1c6cf265.js")
R.m(80959)
module.exports=R.m(80959).exports
