// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/dashboard" | "/dashboard/auto-replies" | "/dashboard/auto-replies/[id]" | "/dashboard/auto-replies/new" | "/dashboard/gerencial" | "/dashboard/importacoes/cadastros" | "/dashboard/importacoes/editar/[id]" | "/dashboard/importacoes/followup-global" | "/dashboard/importacoes/historico" | "/dashboard/importacoes/novo" | "/dashboard/inbox" | "/dashboard/layouts" | "/dashboard/master" | "/dashboard/master/assistente-tecnico" | "/dashboard/master/exclusoes" | "/dashboard/messages" | "/dashboard/webscraping" | "/dashboard/website" | "/dashboard/whatsapp" | "/hbx-recovery" | "/login" | "/register" | "/reset-password"
type AppRouteHandlerRoutes = "/webhooks/whatsapp"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/hbx/static/[[...path]]" | "/hbx/webscraping" | "/hbx/webscraping/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/dashboard": {}
  "/dashboard/auto-replies": {}
  "/dashboard/auto-replies/[id]": { "id": string; }
  "/dashboard/auto-replies/new": {}
  "/dashboard/gerencial": {}
  "/dashboard/importacoes/cadastros": {}
  "/dashboard/importacoes/editar/[id]": { "id": string; }
  "/dashboard/importacoes/followup-global": {}
  "/dashboard/importacoes/historico": {}
  "/dashboard/importacoes/novo": {}
  "/dashboard/inbox": {}
  "/dashboard/layouts": {}
  "/dashboard/master": {}
  "/dashboard/master/assistente-tecnico": {}
  "/dashboard/master/exclusoes": {}
  "/dashboard/messages": {}
  "/dashboard/webscraping": {}
  "/dashboard/website": {}
  "/dashboard/whatsapp": {}
  "/hbx-recovery": {}
  "/hbx/static/[[...path]]": { "path"?: string[]; }
  "/hbx/webscraping": {}
  "/hbx/webscraping/[[...path]]": { "path"?: string[]; }
  "/login": {}
  "/register": {}
  "/reset-password": {}
  "/webhooks/whatsapp": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
