// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/dashboard/auto-replies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/auto-replies/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/auto-replies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/auto-replies/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/auto-replies/new">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/auto-replies/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/auto-replies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/auto-replies">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/auto-replies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/gerencial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/gerencial">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/gerencial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/importacoes/cadastros/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/importacoes/cadastros">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/importacoes/cadastros/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/importacoes/editar/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/importacoes/editar/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/importacoes/editar/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/importacoes/followup-global/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/importacoes/followup-global">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/importacoes/followup-global/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/importacoes/historico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/importacoes/historico">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/importacoes/historico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/importacoes/novo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/importacoes/novo">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/importacoes/novo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/inbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/inbox">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/inbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/layouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/layouts">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/layouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/master/assistente-tecnico/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/master/assistente-tecnico">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/master/assistente-tecnico/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/master/exclusoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/master/exclusoes">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/master/exclusoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/master/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/master">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/master/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/messages">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/webscraping/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/webscraping">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/webscraping/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/website/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/website">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/website/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/dashboard/whatsapp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/whatsapp">> = Specific
  const handler = {} as typeof import("../../../src/app/dashboard/whatsapp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/hbx-recovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hbx-recovery">> = Specific
  const handler = {} as typeof import("../../../src/app/hbx-recovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reset-password">> = Specific
  const handler = {} as typeof import("../../../src/app/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/webhooks/whatsapp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/webhooks/whatsapp">> = Specific
  const handler = {} as typeof import("../../../src/app/webhooks/whatsapp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
