export const HBX_SEGMENT_SUGGESTIONS = [
  "academias",
  "acessórios automotivos",
  "açougues",
  "advocacias",
  "agências de marketing",
  "agências de turismo",
  "agronegócios",
  "alarmes e segurança",
  "alimentos naturais",
  "aluguel de equipamentos",
  "auto elétricas",
  "auto escolas",
  "auto peças",
  "bares",
  "barbearias",
  "bicicletarias",
  "bijuterias",
  "borracharias",
  "buffets",
  "cafeterias",
  "calçados",
  "casa de carnes",
  "casas de festas",
  "centros automotivos",
  "chaveiros",
  "clínicas de estética",
  "clínicas médicas",
  "clínicas odontológicas",
  "clínicas veterinárias",
  "colégios",
  "comércio varejista",
  "concessionárias",
  "confeitarias",
  "construtoras",
  "contabilidades",
  "consultorias empresariais",
  "corretoras de seguros",
  "cosméticos",
  "coworkings",
  "cursos profissionalizantes",
  "dedetizadoras",
  "depósitos de bebidas",
  "despachantes",
  "distribuidoras",
  "docerias",
  "e-commerce",
  "educação infantil",
  "elétricas",
  "eletrodomésticos",
  "eletrônicas",
  "energia solar",
  "engenharias",
  "escolas",
  "escritórios administrativos",
  "escritórios de arquitetura",
  "estacionamentos",
  "estúdios de fotografia",
  "eventos",
  "farmácias",
  "ferragens",
  "financeiras",
  "floriculturas",
  "fornecedoras industriais",
  "funerárias",
  "gráficas",
  "hospedagens",
  "hotéis",
  "imobiliárias",
  "indústrias alimentícias",
  "indústrias metalúrgicas",
  "informática",
  "instaladoras",
  "joalherias",
  "laboratórios",
  "lanchonetes",
  "lava rápidos",
  "lavanderias",
  "lojas de brinquedos",
  "lojas de celulares",
  "lojas de colchões",
  "lojas de conveniência",
  "lojas de eletrônicos",
  "lojas de móveis",
  "lojas de roupas",
  "lojas de tintas",
  "lotéricas",
  "madeireiras",
  "manutenção predial",
  "marcenarias",
  "materiais de construção",
  "marmorarias",
  "mecânicas",
  "mercados",
  "metalúrgicas",
  "moda feminina",
  "moda masculina",
  "motéis",
  "oficinas mecânicas",
  "ótica",
  "panificadoras",
  "papelarias",
  "perfumarias",
  "pet shops",
  "pizzarias",
  "postos de combustível",
  "provedores de internet",
  "quadras esportivas",
  "químicas",
  "restaurantes",
  "revendas de veículos",
  "salões de beleza",
  "serralherias",
  "serviços contábeis",
  "serviços de limpeza",
  "serviços gráficos",
  "serviços jurídicos",
  "serviços médicos",
  "serviços odontológicos",
  "serviços terceirizados",
  "sistemas de segurança",
  "supermercados",
  "telecomunicações",
  "transportadoras",
  "turismo",
  "uniformes",
  "universidades",
  "usinagem",
  "vidraçarias",
  "vigilância",
  "vistorias veiculares",
  "web design",
  "xérox e copiadoras",
  "yoga e pilates",
  "zeladoria",
];

export const HBX_PF_NICHE_SUGGESTIONS = [
  "plano de saúde",
  "seguros",
  "consórcio",
  "imóveis",
  "energia solar",
  "crédito",
  "estética",
  "serviços",
];
